dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
  - $C:\Users\mrkro\.m2

script:
  - cd sandwich-shop-manager
  - mvn clean install